### ISSUE TITLE
checkbox render on WaxForm

### ISSUE THREAD

**Issue by joeturner** [phpwax/phpwax#26]
using the following in the model

$this->define("tandc_agree", "IntegerField", array('widget'=>'CheckboxInput') );

renders the following html in the view

<input type="checkbox" name="feedback[tandc_agree]" value="" id="feedback_tandc_agree" class="input_field checkbox_field valid-length"  />
<label for="feedback_tandc_agree">Tandc agree</label>

missing a value on the checkbox, and the hidden version of the element to cover when checkbox isn't clicked missing altogether.
The other issue is when set to required, validation fails whether its checked or not.

Pesky checkbox!

**Comment by charlesmarshall** [comment]
will have a look and see whats going on

**Comment by charlesmarshall** [comment]
few issues behind this one...
- rendering the hidden:
  output var was over wrote rather than appended
- validation
  validations on widgets werent being passed down to the waxmodelfield
  the checkbox widget didnt call parent

Also noticed that validations called the func straight away without making sure the function existed; added a method_exists

I have a working version locally, im testing at the moment and will push when checked some older sites.

**Comment by charlesmarshall** [comment]
pushing now if you want to give it a try...

**Comment by charlesmarshall** [comment]
closing...

**Comment by joeturner** [comment]
looks like its working bang on buddy! nice work. having a flick through the updates now.
